"""Add in tables for user onboarding

Revision ID: 84b6f887a401
Revises: 
Create Date: 2024-07-21 13:25:42.382314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b6f887a401'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('current_conditioning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runner_id', sa.Integer(), nullable=True),
    sa.Column('runner_age', sa.Integer(), nullable=True),
    sa.Column('years_running', sa.Integer(), nullable=True),
    sa.Column('current_weekly_miles', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('future_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runner_id', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('pace', sa.String(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('run_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runner_id', sa.Integer(), nullable=True),
    sa.Column('five_k_record', sa.Integer(), nullable=True),
    sa.Column('ten_k_record', sa.Integer(), nullable=True),
    sa.Column('half_marathon_record', sa.Integer(), nullable=True),
    sa.Column('marathon_record', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runner_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runner_id', sa.Integer(), nullable=True),
    sa.Column('race_training', sa.Boolean(), nullable=True),
    sa.Column('base_building', sa.Boolean(), nullable=True),
    sa.Column('weekly_mileage', sa.Integer(), nullable=True),
    sa.Column('weekly_sessions', sa.Integer(), nullable=True),
    sa.Column('weight_training', sa.Boolean(), nullable=True),
    sa.Column('cross_training', sa.Boolean(), nullable=True),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runner_goals')
    op.drop_table('personal_records')
    op.drop_table('future_runs')
    op.drop_table('current_conditioning')
    op.drop_table('runners')
    # ### end Alembic commands ###
