"""Add race column to runner_goals

Revision ID: f2eee63cf004
Revises: 84b6f887a401
Create Date: 2024-07-22 16:35:20.244117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2eee63cf004'
down_revision = '84b6f887a401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runner_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runner_goals', schema=None) as batch_op:
        batch_op.drop_column('race')

    # ### end Alembic commands ###
